### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by mikaelgithub** [mikaelgithub/SEBC#3]

**Comment by mikaelgithub** [comment]
I am encountering an issue as I am doing this lab post kerberization of the cluster.
I am stuck here : setting up the "Cluster-wide Advanced Configuration Snippet (Safety Valve) for core-site.xml" in the configuration of HDFS. This value is not working:
<property><name>hadoop.proxyuser.gffernandez.groups</name><value>*</value></property><property><name>hadoop.proxyuser.gffernandez.hosts</name><value>*</value></property>
Using BDR, the replication task fails : "HDFS replication command failed. "

**Comment by mfernest** [comment]
There's any number of things that might have gone wrong here. Without more evidence of the work done and some log reports I wouldn't know where to start.

**Comment by mfernest** [comment]
Did not submit lab work for HDFS snapshots, NameNode HA, CM user modifications.
